fragment PageParts on Page {
  __typename
  title
  description
  heroTitle
  heroSubtitle
  heroImage
  body
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  siteName
  tagline
  logo
  navigation {
    __typename
    label
    href
    external
  }
  footer {
    __typename
    copyright
    privacyLink
  }
  social {
    __typename
    slack
    youtube
  }
}
